version: '3.8'

services:
  bus_ticket_booking_db:
    image: postgres:15
    container_name: bus_ticket_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: busTicketBooking
    ports:
      - "5439:5432"
    volumes:
      - bus_ticket_booking_db_data:/var/lib/postgresql/data

volumes:
  bus_ticket_booking_db_data: